name: Packer Build and Deploy

on:
  push:
    tags: ["v[0-9].[0-9]+.[0-9]+"]
    branches:
      - "development"
      - "staging"
      - "main"

env:
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
  HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
  HCP_ORGANIZATION_ID: ${{ secrets.HCP_ORGANIZATION_ID }}
  HCP_BUCKET_NAME: "ubuntu-2204-lts"
  azure_client_id: ${{ secrets.ARM_CLIENT_ID }}
  azure_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
  azure_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  azure_tenant_id: ${{ secrets.ARM_TENANT_ID }}
  template_version: 1.0.0

jobs:
  build-image:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      iteration_id: ${{ steps.hcp.outputs.iteration_id }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Rebuild PEM from Base 64 Content
        id: create_pem
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'cert.pem'
          encodedString: ${{ secrets.PEM_BASE64_CONTENT }}
      
      - name: Store filename as Environment Variable
        env:
          PFX_PATH: ${{ steps.create_pem.outputs.filePath }}
        run: packer --version

      - name: Packer Init
        run: packer init .

      - name: Packer Build - Branches
        if: "startsWith(github.ref, 'refs/heads/')"
        run: packer build .

      - name: Packer Build - Tags
        if: startsWith(github.ref, 'refs/tags/v')
        run: HCP_PACKER_BUILD_FINGERPRINT=$(date +'%m%d%YT%H%M%S') packer build .

      - name: Get HCP Packer Iteration ID from Packer Manifest
        id: hcp
        run: |
          last_run_uuid=$(jq -r '.last_run_uuid' "./packer_manifest.json")
          build=$(jq -r '.builds[] | select(.packer_run_uuid == "'"$last_run_uuid"'")' "./packer_manifest.json")
          iteration_id=$(echo "$build" | jq -r '.custom_data.iteration_id')
          echo "::set-output name=iteration_id::$iteration_id"
  update-hcp-packer-channel:
    name: Update HCP Packer channel
    needs: ["build-image"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create and set channel
        working-directory: .github/scripts
        run: |
          channel_name=$( echo ${{github.ref_name}} | sed 's/\./-/g')
          ./create_channel_iteration.sh $HCP_BUCKET_NAME $channel_name "${{ needs.build-image.outputs.iteration_id }}"
