name: Packer Build

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Print Packer Version
      - name: Print Packer Version
        uses: hashicorp/packer-github-actions@v0.2.0
        with:
          command: version
      
      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@v0.2.0
        with:
          command: validate
          arguments: -syntax-only
          target: ubuntu_2204_lts_apache.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@v0.2.0
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: ubuntu_2204_lts_apache.pkr.hcl
        env:
          PACKER_LOG: 1
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
          azure_client_id: ${{ secrets.ARM_CLIENT_ID }}
          azure_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
          azure_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.ARM_TENANT_ID }}
